// User Actions
export const SET_USER_INFORMATION = 'SET_USER_INFORMATION';
export const SET_ACTIVE_CARD = 'SET_ACTIVE_CARD';
export const SET_NEXT_EXPLANATION_CARD = 'SET_NEXT_EXPLANATION_CARD'

// Fractional Still Actions
export const GET_FRACTIONAL_GRAPH_DATA = 'GET_FRACTIONAL_GRAPH_DATA'
export const GET_RUN_OVERVIEW = 'GET_RUN_OVERVIEW'

// Pot Still Actions
export const GET_POT_GRAPH_DATA = 'GET_POT_GRAPH_DATA';
export const GET_POT_RUN_OVERVIEW = 'GET_POT_RUN_OVERVIEW';
